### ISSUE TITLE
Do not set generic canonical link in index.html

### ISSUE THREAD

**Issue by paulroemer** [vaadin/directory#70]
Looks like Google picks up the first canonical link it finds and does not wait for /directory to update it. Generic canonical link is set here: https://github.com/vaadin/directory/blob/main/frontend/index.html#L8

Result is:
![URL Inspection 2024-07-04 at 11 56 34 AM](https://github.com/vaadin/directory/assets/16225666/6abeb923-b688-4dd0-bd10-1e72e5f3f356)

If you check the page when the DOM is fully loaded, the canonical link is correct (i.e. it was updated as expected).

Solution:
Do not set the generic canonical link in the index.html. Even if Google cannot find any canonical link after the removal anymore, it is still better to have no instead of a wrong canonical link.

**Comment by paulroemer** [comment]
Another solution: Make sure the correct canonical is set with the help of an index boot strap listener.

**Comment by samie** [comment]
Investigated this and these should be replaced in [HtmlHeaderController.java](https://github.com/vaadin/directory/blob/main/src/main/java/org/vaadin/directory/HtmlHeaderController.java#L64) with the correct URL:
```
<link rel="canonical" href="https://vaadin.com/directory/component/moneyfield">
```

However, the problem seems to be the version number that might lead to situation when the replace does not happen correctly.

To test run: 
```
curl https://vaadin.com/directory/component/moneyfield/1.0.0
```

**Comment by samie** [comment]
Deployed. Verified that also `curl https://vaadin.com/directory/component/moneyfield/1.0.0` now correctly returns `<link rel="canonical" href="https://vaadin.com/directory/component/moneyfield">`.
